export function onboardingProtocolLines(): string[] {
  return [
    'This is **global context onboarding**, not repo-local onboarding.',
    'Ask **one question at a time** and keep using the saved workflow language all the way through.',
    'Wait for the user\'s first answer before you inspect docs, repos, directories, or files on your own.',
    'Start by asking the user to paste or share organized docs or reference material if they have any; otherwise ask what kind of work they mainly do.',
    'Do **not** start with a repo scan, a company guess, or a broad hypothesis built from directories like `~/sources`.',
    'Do **not** ask for a full information dump up front.',
    'If docs, reference material, or reference paths are provided, read those first, summarize your understanding back, ask whether that summary is correct before continuing, and skip any questions the docs already answered well.',
    'If no docs are available, continue from the user\'s own description first, then after the user\'s first answer, proactively inspect related repos, docs, paths, and workflows that appear materially connected.',
    'Use bounded local inspection to confirm or challenge the user\'s description instead of waiting for the user to enumerate every related repo manually.',
    'Do **not** scan broad directories or inspect every source file; prefer docs, READMEs, summaries, and a few pointed paths first.',
    'Then ask whether anything important is still missing or worth adding before you continue into deeper discovery.',
    'When you do present a hypothesis, offer only these structured numbered confirmations: 1. This is mostly correct. 2. Some parts are wrong. Please explain what differs. 3. Most of this is wrong. Please explain the right frame.',
    'If the user picks 2 or 3, ask only for the delta, correction, or right frame instead of restarting from scratch.',
    'Do **not** start by asking what one repository does.',
    'Only ask the user who they are, what kind of person they are in the organization, and what work they usually own or lead after the provided docs or description still leave real gaps.',
    'Ask next for one core recurring work type only when the provided docs or description still do not make the work types clear, then ask whether there are more work types to capture.',
    'For each work type, ask how that work shows up day to day.',
    'Only after the work types are clear should you ask which repositories are involved in each work type.',
    'Once the user names concrete repositories, do not ask them to explain those repositories from scratch when recoverable local evidence exists.',
    'For each repository that can be inspected locally, read the strongest available evidence first (README, docs, package metadata, top-level entrypoints, deployment/config files, and a few pointed paths), then present your current understanding back as a short hypothesis.',
    'After that repository-level hypothesis, ask the user to choose only one structured confirmation: 1. This is mostly correct. 2. Some parts are wrong. Please explain what differs. 3. Most of this is wrong. Please explain the right frame.',
    'When local evidence already covers the repository role, important paths, workflow, or conventions well enough, skip the open-ended questions and ask only for missing deltas.',
    'Only ask open-ended repository questions when the needed detail cannot be recovered responsibly from local evidence.',
    'After the user\'s first answer, proactively inspect relevant local repos, docs, paths, and workflows whenever the connection is strong enough to test your current frame.',
    'Ask whether there are additional repositories for the current work type before moving on.',
    'After repository coverage, ask for company/domain glossary terms and acronyms that should become durable context.',
    'Then ask which verification commands should be treated as defaults for this kind of work.',
    'Synthesize the interview into an encyclopedia-style context set with many small docs instead of a few broad docs.',
    'Prefer category directories such as `docs/role/`, `docs/repos/`, `docs/domain/`, `docs/workflows/`, `docs/conventions/`, and `docs/infra/` whenever that split fits the material.',
    'Prefer one concept, one repository, one workflow, or one convention per file when possible.',
    'Treat `index.md` as concept-first: show the keywords a user or AI would search for, not just broad document titles.',
    'Generate index entries automatically from primary concept names, aliases, repository nicknames, and workflow labels when those are clear.',
    'Split glossary docs when a concept is likely to be searched directly, needs more than a short definition, or carries workflow/constraint details; keep only low-value leftover terms in a shared glossary.',
    'Keep each doc summary-first so the top section gives the gist before deeper details.',
    'Treat `index.md` as a human-readable dictionary-style table of contents grouped by category headings and `label -> path` entries.',
  ];
}

export function onboardingCompletionLines(): string[] {
  return [
    'Before you claim onboarding is complete, run `gctree verify-onboarding --branch <current-gc-branch>` and inspect the real gc-tree files.',
    'Do not claim onboarding is complete unless verification returns `status: "complete"`.',
    'After applying the onboarding docs, explicitly list which durable docs were saved.',
    'Then summarize what you now understand from the saved docs instead of stopping at the filenames alone.',
    'For that final summary, do not ask an open-ended validation question first; present the summary and ask the user to choose only one structured confirmation: 1. This matches well enough. 2. Some parts are wrong. I will give the delta. 3. The frame is wrong. I will restate it.',
    'If the user picks 2 or 3 for the final summary, ask only for the correction delta or replacement frame, then update the saved understanding instead of restarting the interview.',
    'Ask whether anything else should be saved while the context is still fresh.',
    'After docs are confirmed correct, do not ask the user to recall repo-scope mappings from scratch; propose the concrete repository candidates that appear materially tied to this gc-branch, then ask the user to choose only one structured confirmation: 1. Map these candidates. 2. Map these, but with corrections. 3. Skip repo mapping for now.',
    'If the user picks 2 for repo mapping, ask only for the repo delta to add or remove. If the user picks 1 or gives corrected candidates, navigate to each confirmed repository and run `gctree set-repo-scope --branch <current-gc-branch> --include`. Skip mapping only if the user picks 3 or explicitly says mapping is not needed.',
    'Do not finish onboarding while material related repos, workflows, or domain terms remain uninspected when recoverable local evidence is still available.',
    'Only after the related repos, workflows, glossary, default verification commands, and repo-scope mapping are either captured or explicitly skipped should you wrap up, then remind the user that future changes belong in `gctree update-global-context`.',
  ];
}
